name: CI/CD Pipeline

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python (if using Python project)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run tests
        run: pytest

      # 5. Build (for example, package project)
      - name: Build project
        run: |
          echo "Building the project..."
          mkdir build
          cp -r * build/

      # 6. Deploy (example: simulate deployment)
      - name: Deploy
        run: |
          echo "Deploying application..."
          # Replace this with real deployment steps
          # Example: scp build/* user@server:/var/www/app
