name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t .
          zip -r lambda_package.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:760812854335:function:lamda_func \
            --zip-file fileb://lambda_package.zip
      - name: Verify Deployment
        run: |
          echo "Fetching latest Lambda configuration..."
          aws lambda get-function-configuration \
            --function-name lambda_func \
            --query '{LastModified:LastModified, Runtime:Runtime, Handler:Handler, FunctionName:FunctionName}' \
            --output table

      - name: Test Invoke Lambda
        run: |
          echo "Invoking Lambda with test payload..."
          aws lambda invoke \
            --function-name lambda_func \
            --payload '{"test":"hello"}' \
            response.json
          echo "Lambda response:"
          cat response.json